# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panelgen < Formula
  desc "AI image series generator for comics and carousels"
  homepage "https://github.com/raphink/panelgen"
  version "1.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raphink/panelgen/releases/download/v1.3.1/panelgen_1.3.1_darwin_amd64.tar.gz"
      sha256 "0623573b5df94e1bad7644fa537116442d89419820c8fdcfc0f802f874639368"

      define_method(:install) do
        bin.install "panelgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raphink/panelgen/releases/download/v1.3.1/panelgen_1.3.1_darwin_arm64.tar.gz"
      sha256 "baeb56eb1512d9b3b8811557f6a433316f7d1904d69f44b89b2e39eba4ff582f"

      define_method(:install) do
        bin.install "panelgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphink/panelgen/releases/download/v1.3.1/panelgen_1.3.1_linux_amd64.tar.gz"
      sha256 "d0c65bf1864a877a510d9faeb49ed12354613ce8f30405722e1b73762b814df6"
      define_method(:install) do
        bin.install "panelgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphink/panelgen/releases/download/v1.3.1/panelgen_1.3.1_linux_arm64.tar.gz"
      sha256 "4c17c4ab8e6576acf88ab763634ceda261a92e65f1973c2ddd7212c414f74f37"
      define_method(:install) do
        bin.install "panelgen"
      end
    end
  end

  test do
    system "#{bin}/panelgen", "version"
  end
end
