# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Panelgen < Formula
  desc "AI image series generator for comics and carousels"
  homepage "https://github.com/raphink/panelgen"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raphink/panelgen/releases/download/v0.2.2/panelgen_0.2.2_darwin_amd64.tar.gz"
      sha256 "fde51dc075396d5773b0b2f59a32f8d56befadc0f90d4bd4b5e1480f863093ca"

      define_method(:install) do
        bin.install "panelgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raphink/panelgen/releases/download/v0.2.2/panelgen_0.2.2_darwin_arm64.tar.gz"
      sha256 "550fef7392478e6168d4d656e8d11d8362e1452535ffcdc5f833da4e835393ff"

      define_method(:install) do
        bin.install "panelgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphink/panelgen/releases/download/v0.2.2/panelgen_0.2.2_linux_amd64.tar.gz"
      sha256 "538f0ca8fa50c7c39d6ba381ac17c97c7c2729952089674fcecadf21165815cd"
      define_method(:install) do
        bin.install "panelgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raphink/panelgen/releases/download/v0.2.2/panelgen_0.2.2_linux_arm64.tar.gz"
      sha256 "edcc23a302353dc186b00015672c4b7c6257ab38fea05ba874e160b63ef8d1bf"
      define_method(:install) do
        bin.install "panelgen"
      end
    end
  end

  test do
    system "#{bin}/panelgen", "version"
  end
end
